-- ============================================================================
-- 配套：云端序列保险 RPC（防同步写入高 id 后本地自增撞号）
--
-- 背景：cases/intakes/timeline/expenses 改为 GENERATED BY DEFAULT 后，syncOps
--       会把 NAS 侧的显式 id 写进云端。若云端自增序列仍低于这些 id，之后云端
--       原生 INSERT（省略 id）自增到该值时就会主键冲突。
--
-- 作用：sync 每写完云端一侧，调用本函数把对应表的 owned 序列顶到 max(id)+1，
--       确保云端后续自增永不撞上已同步进来的 NAS id。幂等、只读序列、不改数据。
--
-- 安全：SECURITY DEFINER（以库 owner 执行 setval，service_role 才能调）；
--       仅对传入表名操作，调用方传表名，不拼任意 SQL。
-- ============================================================================

create or replace function public.sync_bump_seq(p_tbl text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  seq text;
  mx  bigint;
begin
  if p_tbl not in ('cases','intakes','timeline','expenses',
                   'contacts','materials','case_folders') then
    raise notice 'sync_bump_seq: 未知表 %，跳过', p_tbl;
    return;
  end if;
  seq := pg_get_serial_sequence(format('public.%I', p_tbl), 'id');
  if seq is not null then
    execute format('select coalesce(max(id),0) from public.%I', p_tbl) into mx;
    perform setval(seq, mx + 1, false);
    raise notice 'sync_bump_seq: % 序列对齐到 %', p_tbl, mx + 1;
  end if;
end $$;

grant execute on function public.sync_bump_seq(text) to authenticated, service_role;
