-- ============================================================================
-- 修复：vault_meta 在多租户下「只能存在一行」的结构缺陷
--
-- 症状：第一个人设置敏感信息密码正常，之后任何人设置都失败
--       （撞主键 / 被 RLS 拒绝 —— RLS 只允许改 user_id = 自己的行）。
--
-- 根因：原定义为
--         id  smallint primary key default 1
--       id 默认恒为 1，而主键不允许重复 ⇒ 全表最多一行。
--       配合旧前端「写死 id=1 做 upsert」，多租户场景必然崩。
--
-- 修复：id 改为自增，配合 unique(user_id) 实现「每用户一条」。
--       前端同步改为按 user_id 定位（on_conflict=user_id），不再写死 id。
--
-- 适用范围：**公开多租户库必须执行**；自建库若只你一人用，当前不出错，
--       但为了与统一结构一致，建议一并执行。
-- ============================================================================

-- 1) 去掉「恒为 1」的默认值
alter table public.vault_meta alter column id drop default;

-- 2) 改为自增（BY DEFAULT：允许显式插入 id，方便回灌历史数据）
do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name   = 'vault_meta'
      and column_name  = 'id'
      and column_default is not null
  ) then
    alter table public.vault_meta alter column id add generated by default as identity;
    raise notice 'vault_meta.id 已改为自增';
  else
    raise notice 'vault_meta.id 已有默认值，跳过';
  end if;
end $$;

-- 3) 序列对齐到现有最大值，否则新插入会撞已有主键
do $$
declare
  seq text;
  mx  smallint;
begin
  seq := pg_get_serial_sequence('public.vault_meta', 'id');
  if seq is not null then
    select coalesce(max(id), 0) into mx from public.vault_meta;
    perform setval(seq, mx + 1, false);
    raise notice 'vault_meta.id 序列已对齐到 %', mx + 1;
  end if;
end $$;

-- 4) 确保有 unique(user_id)：前端按 on_conflict=user_id 做 upsert，依赖这个唯一约束
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.vault_meta'::regclass and contype = 'u'
  ) then
    alter table public.vault_meta add constraint vault_meta_user_unique unique (user_id);
    raise notice '已补上 unique(user_id)';
  else
    raise notice 'unique 约束已存在，跳过';
  end if;
end $$;

-- 5) 给已有的那一行补 user_id（若为空）——填你自己的登录邮箱
do $$
declare
  owner_email text := '你的邮箱@example.com';   -- ⚠️ 改成你的邮箱
  owner_uid   uuid;
begin
  select id into owner_uid from auth.users where email = owner_email limit 1;
  if owner_uid is not null then
    update public.vault_meta set user_id = owner_uid where user_id is null;
    raise notice '已为历史行补 user_id = %', owner_uid;
  else
    raise notice '未找到该邮箱账号，跳过（不影响新用户）';
  end if;
end $$;


-- ============================================================================
-- 自检
-- ============================================================================
-- 1) id 应已是自增（column_default 含 nextval / identity）
-- select column_name, column_default, is_identity from information_schema.columns
-- where table_schema='public' and table_name='vault_meta' and column_name='id';

-- 2) 应能看到每个用户各一条（user_id 不同、id 不同）
-- select id, user_id, left(verifier_enc, 12) as verifier_prefix, updated_at
-- from public.vault_meta order by id;

-- 3) 唯一约束应在
-- select conname, contype from pg_constraint where conrelid='public.vault_meta'::regclass;
