-- ============================================================================
-- 修复：云端多租户库 ↔ NAS 双向同步失败（42C9 GENERATED ALWAYS）
--
-- 症状：双向同步「NAS→云端」整批失败，报
--   42C9: Column "id" is an identity column defined as GENERATED ALWAYS
--   （子表 timeline/expenses 因父表 cases 写入失败，连锁 409 外键不存在）
--
-- 根因（已用 Management API 实测 cloud 库 information_schema 确认）：
--   云端 cases / intakes / timeline / expenses 的 id 是 GENERATED ALWAYS，
--   而 syncOps 用 `POST .../{table}?on_conflict=id` 带显式 id 做 upsert，
--   GENERATED ALWAYS 拒绝显式写入 id，于是云端侧写入整批失败。
--
-- 修复：把上述 4 张表的 id 改为 GENERATED BY DEFAULT——允许显式 id，
--       省略 id 时仍由序列自动发号（日常 app 使用方式不变）。
--       其余 4 表（contacts/materials/case_folders/vault_meta）已接受显式 id，不动。
--       仅改 id 发号行为，不改变任何表结构 / RLS / 数据，可反向还原。
--
-- 执行（云端库，用 Management API 的 PAT，或控制台 SQL Editor）：
--   -- 见 lawyer-workbench 仓库说明，PROJECT_REF=eossyfugqwnpqdixmvyy
-- ============================================================================

-- 1) 仅把「当前是 GENERATED ALWAYS」的 4 张表改为 BY DEFAULT（幂等，可重跑）
do $$
declare t text;
begin
  foreach t in array array['cases','intakes','timeline','expenses'] loop
    if exists (
      select 1 from information_schema.columns
      where table_schema='public' and table_name=t and column_name='id'
        and is_identity='YES' and identity_generation='ALWAYS'
    ) then
      execute format('alter table public.%I alter column id set generated by default', t);
      raise notice '%: id -> GENERATED BY DEFAULT', t;
    else
      raise notice '%: 已非 ALWAYS，跳过', t;
    end if;
  end loop;
end $$;

-- 2) 序列对齐到 max(id)+1，避免同步写入较高显式 id 后本地自增撞号
do $$
declare t text; seq text; mx bigint;
begin
  foreach t in array array['cases','intakes','timeline','expenses'] loop
    seq := pg_get_serial_sequence(format('public.%I', t), 'id');
    if seq is not null then
      execute format('select coalesce(max(id),0) from public.%I', t) into mx;
      perform setval(seq, mx + 1, false);
      raise notice '%: 序列 % 对齐到 %', t, seq, mx + 1;
    end if;
  end loop;
end $$;

-- ============================================================================
-- 自检（应返回 4 行 is_identity=YES 且 identity_generation=BY DEFAULT）
-- select table_name, is_identity, identity_generation
-- from information_schema.columns
-- where table_schema='public' and column_name='id'
--   and table_name in ('cases','intakes','timeline','expenses')
-- order by table_name;
-- ============================================================================
