-- ============================================================
-- NAS 自建库（单用户）· 同步墓碑表
--
-- 作用：与云端墓碑表配对。NAS 端删除的行记在这里，同步时据此删掉云端对应行。
--
-- 为什么 NAS 版没有 user_id：NAS 是本人独用的单用户库，所有业务表都没有
-- user_id 列（既有设计），加上反而会让 PostgREST 报「column does not exist」。
--
-- 执行方式（在 NAS 上）：
--   docker exec -i supabase-selfhosted-db-1 psql -U postgres -d postgres < 本文件
-- ============================================================

create table if not exists public.sync_tombstones (
  id         bigint generated by default as identity primary key,
  tbl        text not null,
  row_id     text not null,
  deleted_at timestamptz not null default now()
);

-- 同一张表 + 同一行，只保留一条墓碑（upsert 冲突目标）
create unique index if not exists sync_tombstones_tbl_row_key
  on public.sync_tombstones (tbl, row_id);

-- 单用户库：开 RLS 但策略放行（与「库本身就是自己的」一致，service_role 本就 bypass）
alter table public.sync_tombstones enable row level security;

drop policy if exists sync_tombstones_all on public.sync_tombstones;
create policy sync_tombstones_all on public.sync_tombstones
  for all
  using (true)
  with check (true);

grant select, insert, update, delete on public.sync_tombstones
  to anon, authenticated, service_role;

-- 自检
-- \d public.sync_tombstones
-- select indexname from pg_indexes where tablename = 'sync_tombstones';
