-- ============================================================
-- 云端（多租户 Supabase）· 同步墓碑表
--
-- 作用：记录「我在本库删掉了哪张表的哪一行」，双向同步据此在对端执行删除，
--       避免已删除的数据被当成「对端缺失」又补回来（复活）。
--
-- 为什么云端需要 user_id：云端是所有律师共用的多租户库，同步用 service_role
-- 会绕过 RLS，必须按 user_id 只处理自己的墓碑（与 cases/intakes 等根表一致）。
--
-- 执行位置：Supabase 控制台 → SQL Editor（云端项目）
-- ============================================================

create table if not exists public.sync_tombstones (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null default auth.uid(),
  tbl        text not null,
  row_id     text not null,
  deleted_at timestamptz not null default now()
);

-- 同一用户 + 同一张表 + 同一行，只保留一条墓碑（去重 & upsert 冲突目标）
create unique index if not exists sync_tombstones_uid_tbl_row_key
  on public.sync_tombstones (user_id, tbl, row_id);

create index if not exists sync_tombstones_user_idx
  on public.sync_tombstones (user_id);

-- 行级安全：只能看到/操作自己的墓碑；is_admin() 可越过（运维用）
alter table public.sync_tombstones enable row level security;

drop policy if exists sync_tombstones_owner on public.sync_tombstones;
create policy sync_tombstones_owner on public.sync_tombstones
  for all
  using (user_id = auth.uid() or public.is_admin())
  with check (user_id = auth.uid() or public.is_admin());

-- PostgREST 角色授权（缺了会 401/403）
grant select, insert, update, delete on public.sync_tombstones
  to anon, authenticated, service_role;

-- 自检（执行后应看到 1 条 unique 索引 + RLS 已启用 + 策略存在）
-- select indexname from pg_indexes where tablename = 'sync_tombstones';
-- select relname, relrowsecurity from pg_class where relname = 'sync_tombstones';
-- select policyname from pg_policies where tablename = 'sync_tombstones';
